name: Auto-commit every 3 days

on:
  schedule:
    # Runs every 3 days at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 */3 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for changes and commit
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            timestamp=$(date '+%Y-%m-%d %H:%M:%S UTC')
            git commit -m "Auto-commit: $timestamp"
            git push
            echo "Auto-commit completed at $timestamp"
          fi